import { Storage } from '@google-cloud/storage'

const MAX_PAYLOAD_BYTES = 2 * 1024 * 1024 // 2 MB
const MAX_DESCRIPTION_LENGTH = 2000

export default defineEventHandler(async (event) => {
  // Auth required — prevents anonymous spam of GitHub issues
  const session = await getUserSession(event)
  if (!session?.user) {
    throw createError({ statusCode: 401, message: 'Authentication required' })
  }

  const config = useRuntimeConfig()
  const githubToken = config.githubToken as string
  if (!githubToken) {
    throw createError({ statusCode: 500, message: 'Bug reporting not configured' })
  }

  // Size guard — check Content-Length header first, then verify actual body size after parsing
  const contentLength = Number(getHeader(event, 'content-length') || 0)
  if (contentLength > MAX_PAYLOAD_BYTES) {
    throw createError({ statusCode: 413, message: 'Payload too large' })
  }

  const body = await readBody<{
    description: string
    pageUrl: string
    screenshot: string
    pageState: { route?: string, page?: string }
    environment: { url?: string, viewport?: string, userAgent?: string, timestamp?: string }
  }>(event)

  // Enforce actual body size (catches missing/forged Content-Length and chunked transfer)
  const actualSize = JSON.stringify(body).length
  if (actualSize > MAX_PAYLOAD_BYTES) {
    throw createError({ statusCode: 413, message: 'Payload too large' })
  }

  if (!body.description?.trim()) {
    throw createError({ statusCode: 400, message: 'Description is required' })
  }

  const repo = config.githubRepo as string || 'peter-fusek/contactrefiner'
  const reporter = session.user?.name || session.user?.email || 'Authenticated user'

  // Sanitize inputs — user description and URL could contain anything
  const description = body.description.trim().slice(0, MAX_DESCRIPTION_LENGTH)
  const pagePath = sanitizePath(body.pageUrl)

  // Upload screenshot to GCS and generate a signed URL for the GitHub issue
  // Base64 data URLs are too large for GitHub issue bodies (65536 char limit)
  let screenshotMarkdown = ''
  const SCREENSHOT_PREFIX = /^data:image\/(png|jpeg|webp);base64,/
  if (body.screenshot && body.screenshot.length <= 3 * 1024 * 1024 && SCREENSHOT_PREFIX.test(body.screenshot)) {
    const data = body.screenshot.slice(body.screenshot.indexOf(',') + 1)
    const SAMPLE_RE = /^[A-Za-z0-9+/]+=*$/
    if (SAMPLE_RE.test(data.slice(0, 100)) && SAMPLE_RE.test(data.slice(-100))) {
      try {
        const mimeMatch = body.screenshot.match(/^data:image\/(png|jpeg|webp);/)
        const ext = mimeMatch?.[1] || 'png'
        const mimeType = `image/${ext}`
        const timestamp = Date.now()
        const gcsPath = `data/bug-screenshots/bug-${timestamp}.${ext}`

        const bucket = new Storage().bucket(String(config.gcsBucket))
        const file = bucket.file(gcsPath)
        await file.save(Buffer.from(data, 'base64'), {
          contentType: mimeType,
          resumable: false,
        })

        const [signedUrl] = await file.getSignedUrl({
          action: 'read',
          expires: Date.now() + 90 * 24 * 60 * 60 * 1000, // 90 days
        })

        screenshotMarkdown = [
          '## Screenshot',
          '',
          `![Bug screenshot](${signedUrl})`,
          '',
        ].join('\n')
      }
      catch (uploadErr) {
        console.error('Screenshot upload to GCS failed:', uploadErr instanceof Error ? uploadErr.message : uploadErr)
        screenshotMarkdown = '## Screenshot\n\n*Screenshot was captured but could not be uploaded.*\n'
      }
    }
  }

  // Only allow known safe environment fields (no DOM-scraped content)
  const safeEnv = {
    viewport: String(body.environment?.viewport || '').slice(0, 20),
    timestamp: String(body.environment?.timestamp || '').slice(0, 30),
  }

  const safePageState = {
    route: String(body.pageState?.route || '').slice(0, 200),
    page: String(body.pageState?.page || '').slice(0, 50),
  }

  const pageFiles = mapPageToFile(pagePath)
  const now = new Date().toISOString().slice(0, 19).replace('T', ' ')

  // Wrap user-provided text in code blocks to prevent markdown injection
  const issueBody = [
    '## Bug Report',
    `**Page**: \`${pagePath}\``,
    `**Reporter**: \`${reporter.replace(/`/g, "'")}\``,
    `**Date**: ${now}`,
    '',
    '## What happened',
    '```',
    description,
    '```',
    '',
    screenshotMarkdown,
    '',
    '## Environment',
    '```json',
    JSON.stringify(safeEnv, null, 2),
    '```',
    '',
    '## Page State',
    '```json',
    JSON.stringify(safePageState, null, 2),
    '```',
    '',
    '## Files to Investigate',
    ...pageFiles.map(f => `- \`${f}\``),
    '',
    '---',
    '*Auto-generated by Contact Refiner bug reporter*',
  ].filter(Boolean).join('\n')

  let issueRes: { number: number, html_url: string }
  try {
    issueRes = await $fetch<{ number: number, html_url: string }>(
      `https://api.github.com/repos/${repo}/issues`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
        body: {
          title: `[Bug] ${pagePath}: ${description.slice(0, 80).replace(/[`\n\r]/g, ' ')}`,
          body: issueBody,
          labels: ['bug', 'user-reported'],
        },
      },
    )
  }
  catch (err: unknown) {
    const errMsg = err instanceof Error ? err.message : String(err)
    // Log response details from GitHub API for debugging
    const statusCode = (err as { statusCode?: number })?.statusCode
      || (err as { response?: { status?: number } })?.response?.status
    const responseData = (err as { data?: unknown })?.data
    console.error('GitHub issue creation failed:', {
      message: errMsg,
      statusCode,
      responseData: responseData ? JSON.stringify(responseData).slice(0, 500) : undefined,
      bodySize: issueBody.length,
      hasScreenshot: !!screenshotMarkdown,
    })
    throw createError({ statusCode: 502, message: 'Bug report could not be submitted' })
  }

  return {
    issueNumber: issueRes.number,
    issueUrl: issueRes.html_url,
  }
})

function sanitizePath(url: string | undefined): string {
  if (!url) return '/unknown'
  try {
    const parsed = new URL(url)
    // Only keep the pathname, strip query/hash to avoid injection
    return parsed.pathname.replace(/[^a-zA-Z0-9/\-_]/g, '') || '/unknown'
  }
  catch {
    return '/unknown'
  }
}

function mapPageToFile(path: string): string[] {
  const base = path.split('?')[0].replace(/\/$/, '') || '/dashboard'
  const pageName = base.slice(1) || 'index'

  const files = [
    `dashboard/app/pages/${pageName}.vue`,
  ]

  const apiMap: Record<string, string[]> = {
    'dashboard': ['dashboard/server/api/status.get.ts'],
    'review': ['dashboard/server/api/review/index.get.ts', 'dashboard/server/api/review/decide.post.ts'],
    'changelog': ['dashboard/server/api/changelog.get.ts'],
    'analytics': ['dashboard/server/api/analytics.get.ts'],
    'social-signals': ['dashboard/server/api/social-signals.get.ts'],
    'followup': ['dashboard/server/api/followup-scores.get.ts'],
    'runs': ['dashboard/server/api/pipeline-runs.get.ts'],
    'config': ['dashboard/server/api/config/index.get.ts'],
    'pipeline': [],
  }

  files.push(...(apiMap[pageName] || []))
  return files
}
